api_platform:
    title: 'API MemOlicard'
    show_webby: false
    enable_swagger_ui: true
    enable_re_doc: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    
